<?php

declare(strict_types=1);

namespace Zbmowrey\WeightedLevenshtein\Tests\CrossValidation;

use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use RuntimeException;
use Zbmowrey\WeightedLevenshtein\CharCostMap;
use Zbmowrey\WeightedLevenshtein\CharPairCostMap;
use Zbmowrey\WeightedLevenshtein\Distance;

/**
 * Compares this port's output to fixtures generated by running the original
 * Python weighted-levenshtein library on 600 randomized inputs (200 per
 * algorithm) with random cost overrides. Fixtures live in
 * tests/fixtures/python_reference.json.
 *
 * Regenerate locally with tests/fixtures/regenerate.sh if needed.
 */
#[CoversNothing]
final class PythonReferenceTest extends TestCase
{
    /**
     * @return iterable<string, array{0: array<string, mixed>}>
     */
    public static function fixtureProvider(): iterable
    {
        $path = __DIR__ . '/../fixtures/python_reference.json';
        if (!is_file($path)) {
            throw new RuntimeException('Fixture file missing: ' . $path);
        }
        $raw = file_get_contents($path);
        if ($raw === false) {
            throw new RuntimeException('Could not read fixture file.');
        }
        /** @var array{cases: list<array<string, mixed>>} $data */
        $data = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        foreach ($data['cases'] as $i => $case) {
            $algo = $case['algo'];
            if (!is_string($algo)) {
                throw new RuntimeException('Fixture case missing string "algo" key at index ' . $i . '.');
            }
            yield 'case#' . $i . '/' . $algo => [$case];
        }
    }

    /**
     * @param array<string, mixed> $case
     */
    #[Test]
    #[DataProvider('fixtureProvider')]
    public function matchesPythonReference(array $case): void
    {
        /** @var string $algo */
        $algo = $case['algo'];
        /** @var string $a */
        $a = $case['a'];
        /** @var string $b */
        $b = $case['b'];
        /** @var array<int|string, float> $insert */
        $insert = $case['insert'];
        /** @var array<int|string, float> $delete */
        $delete = $case['delete'];
        /** @var list<array{0: string, 1: string, 2: float}> $substitute */
        $substitute = $case['substitute'];
        /** @var list<array{0: string, 1: string, 2: float}>|null $transpose */
        $transpose = $case['transpose'];
        /** @var float $expected */
        $expected = $case['expected'];

        $insertMap = self::buildCharMap($insert);
        $deleteMap = self::buildCharMap($delete);
        $substituteMap = self::buildPairMap($substitute);
        $transposeMap = $transpose !== null ? self::buildPairMap($transpose) : null;

        $actual = match ($algo) {
            'lev' => Distance::levenshtein($a, $b, $insertMap, $deleteMap, $substituteMap),
            'osa' => Distance::optimalStringAlignment($a, $b, $insertMap, $deleteMap, $substituteMap, $transposeMap),
            'dam_lev' => Distance::damerauLevenshtein($a, $b, $insertMap, $deleteMap, $substituteMap, $transposeMap),
            default => throw new RuntimeException('Unknown algo: ' . $algo),
        };

        self::assertEqualsWithDelta(
            $expected,
            $actual,
            1e-9,
            sprintf(
                '%s(%s, %s) — expected %.12f, got %.12f',
                $algo,
                var_export($a, true),
                var_export($b, true),
                $expected,
                $actual,
            ),
        );
    }

    /**
     * @param array<int|string, float> $overrides Keys may have been coerced to int by json_decode.
     */
    private static function buildCharMap(array $overrides): CharCostMap
    {
        $map = CharCostMap::uniform();
        foreach ($overrides as $char => $cost) {
            $map = $map->withCost((string) $char, $cost);
        }

        return $map;
    }

    /**
     * @param list<array{0: string, 1: string, 2: float}> $overrides
     */
    private static function buildPairMap(array $overrides): CharPairCostMap
    {
        $map = CharPairCostMap::uniform();
        foreach ($overrides as $row) {
            [$from, $to, $cost] = $row;
            $map = $map->withCost($from, $to, $cost);
        }

        return $map;
    }
}
